export const products = [
  {
    name: "Idea Validate",
    description: "Validate your idea with AI",
    icon: "date",
    url: "https://phec.astreak.in/",
    isActive: true,
    tags: ["AI", "Startup", 'Business'],
    category: "Startup",
  },
  {
    name: "Startup Name AI",
    description: "Generate a startup name",
    icon: "time",
    url: "https://phec.astreak.in/name-ai",
    isActive: true,
    tags: ["AI", "Startup", 'Business'],
    category: "Startup",
  },
  {
    name: "Ether Wallet",
    description: "Explore an Ethereum wallet & transactions",
    icon: "time",
    url: "https://ether-explorer-mu.vercel.app/",
    isActive: true,
    tags: ["Ethereum", "Blockchain", "Wallet"],
    category: "Product",
  },
  {
    slug: "",
    name: "Text Tools",
    description: "A collection of text tools",
    icon: "time",
    url: "https://stilltool.vercel.app/",
    isActive: true,
    tags: ["Text"],
    category: "Text",
  },
  {
    slug: "",
    name: "Unity",
    description: "A Package of Unity tools & resources",
    icon: "time",
    url: "https://stilltool.vercel.app/",
    isActive: true,
    tags: ["Npm", 'Package', 'Tool'],
    category: "Package",
  },
];
