export const tools = [
  {
    slug: "email-check",
    name: "Email Validate",
    description: "Validate Email Address",
    icon: "epoch",
    url: "https://still.astreak.in/",
    isActive: true,
    category: "Text",
    tags: ["Text","Email"],
    action: "emailCheck",
    inputs: [
      {
        label: "Email",
        type: "name",
        name: "text",
        required: true,
        key: "email",
      },
    ],
  },
  {
    slug: "phone-check",
    name: "Phone Validate",
    description: "Indian Phone Validation",
    icon: "epoch",
    url: "https://still.astreak.in/phone-check",
    isActive: true,
    category: "Tools",
    tags: ["Number"],
    action: "phoneCheck",
    inputs: [
      {
        label: "Phone",
        placeholder: "Phone Number",
        type: "phone",
        name: "text",
        required: true,
        key: "email",
      },
    ],
  },
  {
    slug: "query-string",
    name: "Query String",
    description: "Parse and build query strings",
    icon: "query-string",
    url: "https://still.astreak.in/query-string",
    isActive: false,
    action: "parseQueryString",
    inputs: [
      {
        label: "Query String",
        placeholder: "Enter query string",
        type: "text",
        name: "query",
        required: true,
      },
    ],
  
  },
  {
    slug: "query-string-builder",
    name: "Query String Builder",
    description: "Build query strings",
    icon: "query-string",
    url: "https://still.astreak.in/query-string-builder",
    isActive: true,
    action: "buildQueryString",
    inputs: [
      {
        label: "Params",
        type: "textarea",
        name: "params",
        required: true,
        key: "params",
      },
    ],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words in a text",
    icon: "word-counter",
    url: "https://still.astreak.in/word-counter",
    isActive: true,
    action: "wordCounter",
    inputs: [
      {
        label: "Text",
        placeholder: "Enter text",
        type: "textarea",
        name: "text",
        required: true,
      },
    ],
  },
  {
    slug: "hash-password",
    name: "Hash Password",
    description: "Hash you Password",
    icon: "epoch",
    url: "https://still.astreak.in/",
    isActive: true,
    action: "hashPassword",
    inputs: [
      {
        label: "Password",
        type: "password",
        name: "password",
        required: true,
        key: "password",
      },
    ],
  },
  {
    slug: "word-to-number",
    name: "Word to Number",
    description: "Convert words to numbers",
    icon: "word-to-number",
    url: "https://still.astreak.in/word-to-number",
    isActive: true,
    action: "wordToNumber",
    inputs: [
      {
        label: "Word",
        placeholder: "Enter word",
        type: "text",
        name: "word",
        required: true,
      },
    ],
  },
  {
    slug: "space-remover",
    name: "Space Remover",
    description: "Remove spaces from a text",
    icon: "space-remover",
    url: "https://still.astreak.in/space-remover",
    isActive: true,
    action: "spaceRemover",
    inputs: [
      {
        label: "Text",
        placeholder: "Enter text",
        type: "textarea",
        name: "text",
        required: true,
      },
    ],
  },
  {
    slug: "line-remover",
    name: "Line Remover",
    description: "Remove lines from a text",
    icon: "line-remover",
    url: "https://still.astreak.in/line-remover",
    isActive: true,
    action: "lineRemover",
    inputs: [
      {
        label: "Text",
        placeholder: "Enter text",
        type: "textarea",
        name: "text",
        required: true,
      },
    ],
  },
  {
    slug: "number-to-word",
    name: "Number to Word",
    description: "Convert numbers to words",
    icon: "number-to-word",
    url: "https://still.astreak.in/number-to-word",
    isActive: true,
    action: "numberToWord",
    inputs: [
      {
        label: "Number",
        placeholder: "Enter number",
        type: "number",
        name: "number",
        required: true,
      },
    ],
  },
  {
    slug: "binary-converter",
    name: "Binary Converter",
    description: "Convert numbers to binary",
    icon: "binary-converter",
    url: "https://still.astreak.in/binary-converter",
    isActive: true,
    action: "binaryConverter",
    inputs: [
      {
        label: "Number",
        placeholder: "Enter number",
        type: "number",
        name: "number",
        required: true,
      },
    ],
  },
  {
    slug: "deep-clone",
    name: "Deep Clone",
    description: "Create a deep clone of an object",
    icon: "deep-clone",
    url: "https://still.astreak.in/deep-clone",
    isActive: true,
    action: "",
    inputs: [
      {
        label: "Object to Clone",
        type: "textarea", // Taking an object in JSON format
        name: "object",
        placeholder: "Enter JSON object",
        required: true,
      },
    ],
  },
  {
    slug: "merge-objects",
    name: "Merge Objects",
    description: "Merge two objects into one",
    icon: "merge-objects",
    url: "https://still.astreak.in/merge-objects",
    isActive: true,
    action: "",
    inputs: [
      {
        label: "First Object",
        type: "textarea", // Taking the first object in JSON format
        name: "object1",
        placeholder: "Enter first JSON object",
        required: true,
      },
      {
        label: "Second Object",
        type: "textarea", // Taking the second object in JSON format
        name: "object2",
        placeholder: "Enter second JSON object",
        required: true,
      },
    ],
  },
  
  
  {
    slug: "regex-check",
    name: "Regex",
    description: "Test a regular expression",
    icon: "regex",
    url: "https://still.astreak.in/",
    isActive: false,
    action: "regexCheck",
    inputs: [
      { label: "Text", type: "text", name: "text", required: true },
      { label: "Pattern", type: "text", name: "pattern", required: true },
    ],
  },
  {
    slug: "",
    name: "Diff",
    description: "Compare two strings",
    icon: "diff",
    url: "https://still.astreak.in/diff",
    isActive: false,
    action: "",
    inputs: [
      { label: "Text 1", type: "text", name: "text1", required: true },
      { label: "Text 2", type: "text", name: "text2", required: true },
    ],
  },
  {
    slug: "",
    name: "JSON Schema",
    description: "Validate JSON against a schema",
    icon: "json-schema",
    url: "https://still.astreak.in/json-schema",
    isActive: false,
    action: "",
    inputs: [
      { label: "JSON", type: "textarea", name: "json", required: true },
      { label: "Schema", type: "textarea", name: "schema", required: true },
    ],
  },
  {
    slug: "",
    name: "JSON Patch",
    description: "Apply a JSON patch",
    icon: "json-patch",
    url: "https://still.astreak.in/json-patch",
    isActive: false,
    action: "",
    inputs: [
      { label: "JSON", type: "textarea", name: "json", required: true },
      { label: "Patch", type: "textarea", name: "patch", required: true },
    ],
  },
  {
    slug: "",
    name: "JSON Pointer",
    description: "Apply a JSON pointer",
    icon: "json-pointer",
    url: "https://still.astreak.in/json-pointer",
    isActive: false,
    action: "",
    inputs: [
      { label: "JSON", type: "textarea", name: "json", required: true },
      { label: "Pointer", type: "text", name: "pointer", required: true },
    ],
  },
  {
    slug: "",
    name: "JSON Merge Patch",
    description: "Apply a JSON merge patch",
    icon: "json-merge-patch",
    url: "https://still.astreak.in/json-merge-patch",
    isActive: false,
    action: "",
    inputs: [
      { label: "JSON", type: "textarea", name: "json", required: true },
      { label: "Patch", type: "textarea", name: "patch", required: true },
    ],
  },
  {
    slug: "",
    name: "JSON Logic",
    description: "Apply a JSON logic expression",
    icon: "json-logic",
    url: "https://still.astreak.in/json-logic",
    isActive: false,
    action: "",
    inputs: [
      { label: "JSON", type: "textarea", name: "json", required: true },
      { label: "Data", type: "textarea", name: "data", required: true },
    ],
  },
  {
    slug: "",
    name: "JSON Query",
    description: "Apply a JSON query",
    icon: "json-query",
    url: "https://still.astreak.in/",
    isActive: false,
    action: "",
    inputs: [
      { label: "JSON", type: "textarea", name: "json", required: true },
      { label: "Query", type: "textarea", name: "query", required: true },
    ],
  },
  {
    slug: "",
    name: "JSON Select",
    description: "Apply a JSON select",
    icon: "json-select",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    slug: "",
    name: "JSON Transform",
    description: "Apply a JSON transform",
    icon: "json-transform",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    slug: "",
    name: "Hash",
    description: "Generate a hash for a string",
    icon: "hash",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    slug: "pdf",
    name: "PDF",
    description: "Convert a webpage to PDF",
    icon: "pdf",
    isActive: true,
  },
  {
    name: "JSON",
    description: "Format JSON",
    icon: "json",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    name: "XML",
    description: "Format XML",
    icon: "xml",
    url: "https://still.astreak.in/",
  },
  {
    name: "CSV",
    description: "Format CSV",
    icon: "csv",
    url: "https://still.astreak.in/",
  },
  {
    name: "YAML",
    description: "Format YAML",
    icon: "yaml",
    url: "https://still.astreak.in/",
  },
  {
    name: "URL",
    description: "Encode or decode a URL",
    icon: "url",
    url: "https://still.astreak.in/",
  },
  {
    name: "Base64",
    description: "Encode or decode base64",
    icon: "base64",
    url: "https://still.astreak.in/",
  },
  {
    name: "JWT",
    description: "Decode a JSON Web Token",
    icon: "jwt",
    url: "https://still.astreak.in/",
  },
  {
    name: "HTML",
    description: "Format HTML",
    icon: "html",
    url: "https://still.astreak.in/",
  },
  {
    name: "CSS",
    description: "Format CSS",
    icon: "css",
    url: "https://still.astreak.in/",
  },
  {
    name: "JavaScript",
    description: "Format JavaScript",
    icon: "javascript",
    url: "https://still.astreak.in/",
  },
  {
    name: "TypeScript",
    description: "Format TypeScript",
    icon: "typescript",
    url: "https://still.astreak.in/",
  },
  {
    name: "Markdown",
    description: "Format Markdown",
    icon: "markdown",
    url: "https://still.astreak.in/",
  },
  {
    name: "Text",
    description: "Format text",
    icon: "text",
    url: "https://still.astreak.in/",
  },
  {
    name: "Image",
    description: "Convert an image to base64",
    icon: "image",
    url: "https://still.astreak.in/",
  },
  {
    name: "Color",
    description: "Convert a color",
    icon: "color",
    url: "https://still.astreak.in/",
  },
  {
    name: "QR Code",
    description: "Generate a QR code",
    icon: "qr",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    slug: "uuid",
    name: "UUID",
    description: "Generate a UUID",
    icon: "uuid",
    url: "https://still.astreak.in/",
    isActive: false,
    action: "uuidGen",
    inputs: [
      {
        label: "Version",
        type: "select",
        name: "version",
        required: true,
        key: "version",
        options: [
          { label: "v1", value: "v1" },
          { label: "v3", value: "v3" },
          { label: "v4", value: "v4" },
          { label: "v5", value: "v5" },
        ],
      },
    ],
  },
  {
    slug: "random",
    name: "Random",
    description: "Generate a random number",
    icon: "random",
    isActive: true,
    action: "randomNumber",
    inputs: [
      { label: "Min", type: "number", name: "min", required: true, key: "min" },
      { label: "Max", type: "number", name: "max", required: true, key: "max" },
    ],
  },


  // Add binary code convertor immage Processing user side
];
