export const tools = [
    {
      name: "Hash",
      description: "Generate a hash for a string",
      icon: "hash",
      url: "https://hash.still.tools",
    },
    {
      name: "PDF",
      description: "Convert a webpage to PDF",
      icon: "pdf",
      url: "https://pdf.still.tools",
    },
    {
      name: "JSON",
      description: "Format JSON",
      icon: "json",
      url: "https://json.still.tools",
    },
    {
      name: "XML",
      description: "Format XML",
      icon: "xml",
      url: "https://xml.still.tools",
    },
    {
      name: "CSV",
      description: "Format CSV",
      icon: "csv",
      url: "https://csv.still.tools",
    },
    {
      name: "YAML",
      description: "Format YAML",
      icon: "yaml",
      url: "https://yaml.still.tools",
    },
    {
      name: "URL",
      description: "Encode or decode a URL",
      icon: "url",
      url: "https://url.still.tools",
    },
    {
      name: "Base64",
      description: "Encode or decode base64",
      icon: "base64",
      url: "https://base64.still.tools",
    },
    {
      name: "JWT",
      description: "Decode a JSON Web Token",
      icon: "jwt",
      url: "https://jwt.still.tools",
    },
    {
      name: "HTML",
      description: "Format HTML",
      icon: "html",
      url: "https://html.still.tools",
    },
    {
      name: "CSS",
      description: "Format CSS",
      icon: "css",
      url: "https://css.still.tools",
    },
    {
      name: "JavaScript",
      description: "Format JavaScript",
      icon: "javascript",
      url: "https://javascript.still.tools",
    },
    {
      name: "TypeScript",
      description: "Format TypeScript",
      icon: "typescript",
      url: "https://typescript.still.tools",
    },
    {
      name: "Markdown",
      description: "Format Markdown",
      icon: "markdown",
      url: "https://markdown.still.tools",
    },
    {
      name: "Text",
      description: "Format text",
      icon: "text",
      url: "https://text.still.tools",
    },
    {
      name: "Image",
      description: "Convert an image to base64",
      icon: "image",
      url: "https://image.still.tools",
    },
    {
      name: "Color",
      description: "Convert a color",
      icon: "color",
      url: "https://color.still.tools",
    },
    {
      name: "QR Code",
      description: "Generate a QR code",
      icon: "qr",
      url: "https://qr.still.tools",
    },
    {
      name: "UUID",
      description: "Generate a UUID",
      icon: "uuid",
      url: "https://uuid.still.tools",
    },
    {
      name: "Random",
      description: "Generate a random number",
      icon: "random",
      url: "https://random.still.tools",
    },
  ];