export const tools = [
  {
    name: "Idea Validate",
    description: "Validate your idea with AI",
    icon: "date",
    url: "https://phec.astreak.in/",
    isActive: true,
    tags: ["AI", "Startup"],
    category: "Startup",
  },
  {
    name: "Startup Name AI",
    description: "Generate a startup name",
    icon: "time",
    url: "https://phec.astreak.in/name-ai",
    isActive: true,
    tags: ["AI", "Startup"],
    category: "Startup",
  },
  {
    name: "Text Tools",
    description: "A collection of text tools",
    icon: "time",
    url: "https://stilltool.vercel.app/",
    isActive: true,
    tags: ["Text"],
    category: "Text",
  },
  {
    name: "Ether Wallet",
    description: "Explore an Ethereum wallet & transactions",
    icon: "time",
    url: "https://ether-explorer-mu.vercel.app/",
    isActive: true,
    tags: ["Ethereum"],
    category: "Ethereum",
  },
  {
    name: "Epoch",
    description: "Convert epoch time to a date",
    icon: "epoch",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    name: "Regex",
    description: "Test a regular expression",
    icon: "regex",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    name: "Diff",
    description: "Compare two strings",
    icon: "diff",
    url: "https://still.astreak.in/diff",
    isActive: false,
  },
  {
    name: "JSON Schema",
    description: "Validate JSON against a schema",
    icon: "json-schema",
    url: "https://still.astreak.in/json-schema",
    isActive: false,
  },
  {
    name: "JSON Patch",
    description: "Apply a JSON patch",
    icon: "json-patch",
    url: "https://still.astreak.in/json-patch",
    isActive: false,
  },
  {
    name: "JSON Pointer",
    description: "Apply a JSON pointer",
    icon: "json-pointer",
    url: "https://still.astreak.in/json-pointer",
    isActive: false,
  },
  {
    name: "JSON Merge Patch",
    description: "Apply a JSON merge patch",
    icon: "json-merge-patch",
    url: "https://still.astreak.in/json-merge-patch",
    isActive: false,
  },
  {
    name: "JSON Logic",
    description: "Apply a JSON logic expression",
    icon: "json-logic",
    url: "https://still.astreak.in/json-logic",
    isActive: false,
  },
  {
    name: "JSON Query",
    description: "Apply a JSON query",
    icon: "json-query",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    name: "JSON Select",
    description: "Apply a JSON select",
    icon: "json-select",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    name: "JSON Transform",
    description: "Apply a JSON transform",
    icon: "json-transform",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    name: "Hash",
    description: "Generate a hash for a string",
    icon: "hash",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    name: "PDF",
    description: "Convert a webpage to PDF",
    icon: "pdf",
    url: "/pdf",
    isActive: true,
  },
  {
    name: "JSON",
    description: "Format JSON",
    icon: "json",
    url: "https://still.astreak.in/",
    isActive: false,
  },
  {
    name: "XML",
    description: "Format XML",
    icon: "xml",
    url: "https://still.astreak.in/",
  },
  {
    name: "CSV",
    description: "Format CSV",
    icon: "csv",
    url: "https://still.astreak.in/",
  },
  {
    name: "YAML",
    description: "Format YAML",
    icon: "yaml",
    url: "https://still.astreak.in/",
  },
  {
    name: "URL",
    description: "Encode or decode a URL",
    icon: "url",
    url: "https://still.astreak.in/",
  },
  {
    name: "Base64",
    description: "Encode or decode base64",
    icon: "base64",
    url: "https://still.astreak.in/",
  },
  {
    name: "JWT",
    description: "Decode a JSON Web Token",
    icon: "jwt",
    url: "https://still.astreak.in/",
  },
  {
    name: "HTML",
    description: "Format HTML",
    icon: "html",
    url: "https://still.astreak.in/",
  },
  {
    name: "CSS",
    description: "Format CSS",
    icon: "css",
    url: "https://still.astreak.in/",
  },
  {
    name: "JavaScript",
    description: "Format JavaScript",
    icon: "javascript",
    url: "https://still.astreak.in/",
  },
  {
    name: "TypeScript",
    description: "Format TypeScript",
    icon: "typescript",
    url: "https://still.astreak.in/",
  },
  {
    name: "Markdown",
    description: "Format Markdown",
    icon: "markdown",
    url: "https://still.astreak.in/",
  },
  {
    name: "Text",
    description: "Format text",
    icon: "text",
    url: "https://still.astreak.in/",
  },
  {
    name: "Image",
    description: "Convert an image to base64",
    icon: "image",
    url: "https://still.astreak.in/",
  },
  {
    name: "Color",
    description: "Convert a color",
    icon: "color",
    url: "https://color.still.tools",
  },
  {
    name: "QR Code",
    description: "Generate a QR code",
    icon: "qr",
    url: "https://qr.still.tools",
  },
  {
    name: "UUID",
    description: "Generate a UUID",
    icon: "uuid",
    url: "https://uuid.still.tools",
  },
  {
    name: "Random",
    description: "Generate a random number",
    icon: "random",
    url: "https://random.still.tools",
  },
];
